Repository wecode-bootcamp-korea/17-1st-Dienstag-backend, pull requests merged in 2021-02, with the labels that each got.

#2 MODIFY: all apps models.py
  cart/__init__.py
  cart/admin.py
  cart/apps.py
  cart/migrations/0001_initial.py
  cart/migrations/0002_cart_user.py
  cart/migrations/0003_auto_20210218_0556.py
  cart/migrations/__init__.py
  cart/models.py
  cart/tests.py
  cart/views.py
  dienstag/settings.py
  product/__init__.py
  product/admin.py
  product/apps.py
  product/migrations/0001_initial.py
  product/migrations/0002_auto_20210218_0155.py
  product/migrations/__init__.py
  product/models.py
  product/tests.py
  product/views.py
  user/__init__.py
  user/admin.py
  user/apps.py
  user/migrations/0001_initial.py
  user/migrations/__init__.py
  user/models.py
  user/tests.py
  user/views.py
  voucher/__init__.py
  voucher/admin.py
  voucher/apps.py
  voucher/migrations/0001_initial.py
  voucher/migrations/__init__.py
  voucher/models.py
  voucher/tests.py
  voucher/views.py
Labels: Status: Accepted

#3 MODIFY : cart/models.py
  cart/migrations/0004_auto_20210219_0335.py
  cart/migrations/0005_auto_20210219_0335.py
  cart/migrations/0006_remove_order_cart.py
  cart/migrations/0007_auto_20210219_0500.py
  cart/migrations/0008_auto_20210219_0500.py
  cart/models.py
  cart/views.py
Labels: Status: Accepted

#4 MODIFY : cart/models.py
  cart/migrations/0009_auto_20210219_0634.py
  cart/migrations/0010_remove_addressinformation_user.py
  cart/migrations/0011_addressinformation_user.py
  cart/migrations/0012_auto_20210219_0957.py
  cart/models.py
  cart/views.py
Labels: Status: Accepted

#6 [17기 허정윤] Modify: (user/views.py) 청구 정보, 배송 정보 입력
  cart/migrations/0001_initial.py
  cart/migrations/0002_cart_user.py
  cart/migrations/0003_auto_20210218_0556.py
  cart/migrations/0004_auto_20210219_0335.py
  cart/migrations/0005_auto_20210219_0335.py
  cart/migrations/0006_remove_order_cart.py
  cart/migrations/0007_auto_20210219_0500.py
  cart/migrations/0008_auto_20210219_0500.py
  cart/migrations/0009_auto_20210219_0634.py
  cart/migrations/0010_remove_addressinformation_user.py
  cart/migrations/0011_addressinformation_user.py
  cart/migrations/0012_auto_20210219_0957.py
  cart/models.py
  dienstag/urls.py
  product/migrations/0001_initial.py
  product/migrations/0002_auto_20210218_0155.py
  user/migrations/0001_initial.py
  user/models.py
  user/urls.py
  user/utils.py
  user/views.py
  voucher/migrations/0001_initial.py
Labels: Status: 리뷰 요청

#10 [17기 허정윤] Modify: (cart/views.py) OrderDetailView 클래스 수정
  cart/urls.py
  cart/views.py
  dienstag/urls.py
Labels: Status: 리뷰 요청

#11 [17기 허정윤] Modify: (user/views.py) SignInView 클래스에서 email 삭제
  user/views.py
Labels: Status: 수정 요청

#7 [17기 안재이] Modify: view.py리뷰사항 반영
  .vimrc
  cart/migrations/0001_initial.py
  dienstag/urls.py
  product/migrations/0001_initial.py
  product/urls.py
  product/views.py
  user/migrations/0001_initial.py
  voucher/migrations/0001_initial.py
Labels: Status: 리뷰 요청
